[project]
name = "oddslib"
version = "0.1.0"
description = "Lightweight odds and probability utilities for Python"
readme = "README.md"
authors = [
    { name = "Reece Colclough", email = "reece.tec@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
