name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install uv and set Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.12

    - name: Clean previous build
      run: make docs-clean

    - name: Build docs (PR validation)
      if: github.event_name == 'pull_request'
      run: make docs

    - name: Build versioned docs
      if: github.event_name != 'pull_request'
      run: make docs-multiversion

    - name: Create redirect to stable docs
      if: github.event_name != 'pull_request'
      run: |
        cat > docs/_build/html/index.html <<'EOF'
        <!DOCTYPE html>
        <html>
          <head>
            <meta http-equiv="refresh" content="0; url=./stable/index.html" />
          </head>
          <body>
            <p>Redirecting to <a href="./stable/index.html">stable documentation</a>...</p>
          </body>
        </html>
        EOF

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        force_orphan: true
