name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
      - name: Execute test suite
        run: uv run --frozen pytest -v

  publish:
    name: Build and publish
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/oddslib/
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
      - name: Build distributions
        run: uv build
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token "$UV_PUBLISH_TOKEN"
